### ISSUE TITLE
For `control` fields with `hw-read: enabled`, `valid` signal isn't really generated, is it expected?

### ISSUE THREAD

**Issue by fxzjshm** [abs-tudelft/vhdmmio#18]
First of all, thank you for the great work!

I'm asking that, for a field with `behavior: control`:
```yaml
  - address: 0
    name: tx_dest_ip_0
    behavior: control
    hw-read: enabled
```
this doesn't really generate statements assigning `f_tx_dest_ip_0_r((0)).v := '1';`;
rather, this requires `after-bus-write: validate`, which further requires `bus-write != masked`:
```yaml
  - address: 0
    name: tx_dest_ip_0
    behavior: control
    hw-read: enabled
    bus-write: enabled
    after-bus-write: validate
```
so is it expected / intended?
(I thought `hw-read: enabled` would imply generating `f_tx_dest_ip_0_r((0)).v := '1';`, before looking through the generated code.)
If not, I think this behavior should be documented, perhaps.
