### ISSUE TITLE
Allow hex values for value of constant behavior register

### ISSUE THREAD

**Issue by mbrobbel** [abs-tudelft/vhdmmio#5]
Currently int and bool values are supported for constant behavior registers. It would be nice if hex values are also supported.

E.g.
```yml
- address: 0
  name: hi
  behavior: constant
  value: 0xc0fefe
```
